name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Backend Dependencies
      run: |
        cd twitter-backend
        npm install
        
    - name: Run Backend Tests
      run: |
        cd twitter-backend
        npm test
      env:
        MONGODB_URI_TEST: mongodb://localhost:27017/social-media-test
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_CALLBACK_URL: ${{ secrets.TWITTER_CALLBACK_URL }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        
    - name: Install Frontend Dependencies
      run: |
        cd twitter-frontend
        npm install
        
    - name: Build Frontend
      run: |
        cd twitter-frontend
        npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy Backend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_BACKEND_PROJECT_ID}}
        working-directory: ./twitter-backend
        vercel-args: '--prod'
        
    - name: Deploy Frontend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID}}
        working-directory: ./twitter-frontend
        vercel-args: '--prod' 